<?xml version="3.0"?>
<package format="3">
  <name>project_sgil</name>
  <version>0.1.0</version>
  <description>A tree-based localization method</description>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>numpy</exec_depend>

  <!-- Add deps here, should match what's in setup.py -->
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-matplotlib</exec_depend>

  <test_depend>pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
